server:
  port: 9528
  max-http-header-size: 10240
  servlet:
    encoding:
      charset: UTF-8
      force: true
    context-path: /collect

spring:
  profiles:
    include: mybatis,kaptcha
    active: dev
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
    serialization:
      indent_output: false