spring:
  redis:
    host: 10.0.5.14
    port: 6379
    password: Meide@123
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 3
        max-wait: 1000ms
      shutdown-timeout: 100ms
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://10.0.5.14:3306/iot?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC&zeroDateTimeBehavior=CONVERT_TO_NULL&allowMultiQueries=true
      username: root
      password: Meide@123
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: MysqlHikariCP
    taosdb:
      driver-class-name: com.taosdata.jdbc.TSDBDriver
      jdbc-url: jdbc:TAOS://10.0.5.14:6030/demo?locale=en_US.UTF-8&timezone=UTC-8&charset=utf-8
      username: root
      password: taosdata
      minimum-idle: 1
      maximum-pool-size: 3
      auto-commit: true
      idle-timeout: 30000
      pool-name: TDengineHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: show tables




